// <auto-generated />
namespace Anonymous_311018.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class databaseversion11addedtwopropertyaddedindepartmenttbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databaseversion11addedtwopropertyaddedindepartmenttbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201811010842450_database version-1.1 added,two property added in department tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
