// <auto-generated />
namespace Anonymous_311018.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class databaseversion10created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databaseversion10created));
        
        string IMigrationMetadata.Id
        {
            get { return "201810311810276_database version-1.0 created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
